import os
import logging
from typing import Optional
from flowsentinel.llm.schemas import AnomalyRiskAssessment
from flowsentinel.config import settings

logger = logging.getLogger(__name__)

class NarrativeGenerator:
    """
    Narrative Generator using Anthropic Claude to turn a structured risk assessment
    into a natural language incident report.
    Falls back to a local template generator if ANTHROPIC_API_KEY is not configured.
    """
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.anthropic_api_key
        if not self.api_key:
            logger.warning("No ANTHROPIC_API_KEY provided. Falling back to local template narrative generator.")
            self.use_llm = False
        else:
            from anthropic import AsyncAnthropic
            self.client = AsyncAnthropic(api_key=self.api_key)
            self.use_llm = True

        # Load system prompt
        current_dir = os.path.dirname(os.path.abspath(__file__))
        prompt_path = os.path.join(current_dir, "prompts", "narrative_system.md")
        try:
            with open(prompt_path, "r", encoding="utf-8") as f:
                self.system_prompt = f.read()
        except FileNotFoundError:
            self.system_prompt = "You are FlowSentinel Incident Reporter."

    async def generate(self, assessment: AnomalyRiskAssessment, language: str = "en") -> str:
        """
        Generates a natural language markdown report in the specified language ('en' or 'es').
        """
        if not self.use_llm:
            return self._generate_fallback(assessment, language)

        prompt = (
            f"Generate a report for the following assessment:\n"
            f"Severity: {assessment.severity}\n"
            f"Rationale: {assessment.rationale}\n"
            f"Recommended Action: {assessment.recommended_action}\n\n"
            f"Please output the report in language: {language.upper()}."
        )

        try:
            response = await self.client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1000,
                system=self.system_prompt,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            # Simple text extraction
            report = ""
            for content in response.content:
                if content.type == "text":
                    report += content.text
            return report.strip()

        except Exception as e:
            logger.error("LLM Narrative generation failed: %s. Using local fallback.", str(e))
            return self._generate_fallback(assessment, language)

    def _generate_fallback(self, assessment: AnomalyRiskAssessment, language: str) -> str:
        if language.lower() == "es":
            title = "REPORTE DE INCIDENTE DE RIESGO DEFI"
            sev_label = "Severidad"
            desc_label = "Detalle del Incidente"
            action_label = "Acción Recomendada"
            gen_label = "Generado por: Generador local basado en reglas de FlowSentinel."
        else:
            title = "DEFI RISK INCIDENT REPORT"
            sev_label = "Severity"
            desc_label = "Incident Description"
            action_label = "Recommended Action"
            gen_label = "Generated by: FlowSentinel Local Template Rule Generator."

        return f"""# {title}

**{sev_label}:** {assessment.severity.upper()}

## {desc_label}
{assessment.rationale}

## {action_label}
{assessment.recommended_action}

---
*{gen_label}*"""
